### ISSUE TITLE
Package status

### ISSUE THREAD

**Issue by tsinis** [DrafaKiller/CodeScanner-flutter#10]
Hey @DrafaKiller and thanks for a great package! What is the status of it? It hasn't been updated for 7 months already, but there have been updates to `google_mlkit_barcode_scanning` since then which might block some projects for updating its internal dependencies on `google_mlkit_*` packages. Thanks again and I hope you are ok!

**Comment by DrafaKiller** [comment]
Thank you for opening an issue about it, and I'm sorry for the inactivity. My attention is currently focused on work, with a large project.

I did attempt to update this package, right when the `google_mlkit_barcode_scanning` package updated, but they changed the way the image is processed

**Comment by DrafaKiller** [comment]
Thank you for opening up an issue about it. I'm sorry for the inactivity. My focus is currently on work because of a large project, and my free time has been challenging to manage due to my university studies.

I attempted to update this package right when the `google_mlkit_barcode_scanning` package updated, but they changed how the image was processed. However, I will try to update this package again once the current project settles. I will take another quick look this week.

Any contributions and improvements you can make are welcome, and I will still gladly review and accept future pull requests!
