### ISSUE TITLE
Not working on web

### ISSUE THREAD

**Issue by Zelfapp** [DrafaKiller/CodeScanner-flutter#3]
The scanner window opens on web, however, neither `onCall` nor `onCallAll` are triggered. I don't see any additional web setup, unless I missed it? I'm attempting to scan using latest Google Chrome.

**Comment by DrafaKiller** [comment]
This issue is similar to issue #2, but it's weird because on that issue was said it works.

Last time I tested it on web, I was having camera permission errors, not sure why, but might be because the package is trying to access the camera too soon, that's just an hypothesis.

If this is the problem, as a workaround, maybe giving a **camera controller** will prevent these issues, since it's not the widget handling the permissions.

---

Either way, the package was originally made just for **Android and iOS** platforms. For some reason pub.dev forcefully updated the package home page and now displays all platforms.

Same as the previous issue, I will look at it whenever I have time, as of right now I'm working on other more important 
projects. Unless someone makes a pull request.

**Comment by DrafaKiller** [comment]
I took a quick look at it, it won't be possible to use or implement this package for Web, MacOS, Windows and Linux.

The Google's ML Kit dependency is only implemented for mobile, and looks like there aren't any easy and quick AI Vision packages for scanning QR Codes and Barcodes outside the mobile environment.

I have tried to fix the pub.dev platform mislabeling, but it has gone nowhere for now.
There's a temporary warning on the package homepage, sorry for the inconvenience.
