### ISSUE TITLE
Why does it scan outside the scanner frame?

### ISSUE THREAD

**Issue by MMA0807** [DrafaKiller/CodeScanner-flutter#5]
Hi! When pointing the camera, until the barcode falls into the scanner frame, the code is already scanned. How do I make sure that the code is scanned only when it hits the scanner frame?

**Comment by DrafaKiller** [comment]
**If with scanner frame you mean the rectangle overlay in the middle**, the overlay is just a guideline, usually gives a better user experience to have something to aim for. That said, it still scans around the overlay.

But **if with scanner frame you mean the camera/screen edges**, I was aware of this. Most devices have the camera resolution different from the screen resolution, most are more square-ish. The image fed to the AI Vision is not the same displayed in the UI.

The scanner fits whatever aspect ratio is in your layout, it's Flutter who decides how to cut it. To have them to be the same, we would have to cut it in the same way Flutter cuts before feeding it to the AI. I already had a commented function to crop the image, but it got tricky to cut the bytes, and I don't know if it would work because the AI may expect a specific resolution.

My only concerns are in terms of performance, as the scanner is working with more than what the user sees. But this wasn't as much of a drawback when scanning only once every second.

---

I'm interested to know what other concerns you have about scanning outside of the frame.

**As a workaround**, you can scan all barcodes using the `onScanAll` callback and ignore all barcodes outside a certain region.
Then you can pick the first one, or if you're feeling adventurous you can pick the one closer to the center.

The barcodes provided have [boundingBox](https://pub.dev/documentation/google_mlkit_barcode_scanning/latest/google_mlkit_barcode_scanning/Barcode/boundingBox.html) and [cornerPoints](https://pub.dev/documentation/google_mlkit_barcode_scanning/latest/google_mlkit_barcode_scanning/Barcode/cornerPoints.html) properties, which have the coordinates of the barcode. Keep in mind you have to use the aspect ratio of the widget relative to the aspect ratio of the camera image, since the widget size and camera image size are not fixed.

**Comment by MMA0807** [comment]
Yes, I mean the rectangle overlay in the middle. How can I fix this?

**Comment by DrafaKiller** [comment]
It's suppose to be like that, there's nothing wrong with scanning everywhere. It's what any other scanner does, like Google Lens.
The overlay is just a suggestion to the user.

---

Like I said, you have a workaround to fix that, you have to do the work yourself though:

> **As a workaround**, you can scan all barcodes using the `onScanAll` callback and ignore all barcodes outside a certain region.
> Then you can pick the first one, or if you're feeling adventurous you can pick the one closer to the center.
> 
> The barcodes provided have [boundingBox](https://pub.dev/documentation/google_mlkit_barcode_scanning/latest/google_mlkit_barcode_scanning/Barcode/boundingBox.html) and [cornerPoints](https://pub.dev/documentation/google_mlkit_barcode_scanning/latest/google_mlkit_barcode_scanning/Barcode/cornerPoints.html) properties, which have the coordinates of the barcode. Keep in mind you have to use the aspect ratio of the widget relative to the aspect ratio of the camera image, since the widget size and camera image size are not fixed.
