### ISSUE TITLE
Question - How to decrease the scan area ?

### ISSUE THREAD

**Issue by ShubhamHande99** [DrafaKiller/CodeScanner-flutter#8]
How to decrease the scan area ?

**Comment by DrafaKiller** [comment]
Currently, it's not possible to decrease the scan area. Since most scanning applications do it, the user is already expecting this behavior without even thinking about it.

It can't be decreased, but you can ignore barcodes based on their position on the screen.
As I already suggested before in issue [#5](https://github.com/DrafaKiller/CodeScanner-flutter/issues/5#issuecomment-1273524701):

> **As a workaround**, you can scan all barcodes using the `onScanAll` callback and ignore all barcodes outside a certain region. Then you can pick the first one, or if you're feeling adventurous you can pick the one closer to the center.
> 
> The barcodes provided have [boundingBox](https://pub.dev/documentation/google_mlkit_barcode_scanning/latest/google_mlkit_barcode_scanning/Barcode/boundingBox.html) and [cornerPoints](https://pub.dev/documentation/google_mlkit_barcode_scanning/latest/google_mlkit_barcode_scanning/Barcode/cornerPoints.html) properties, which have the coordinates of the barcode. Keep in mind you have to use the aspect ratio of the widget relative to the aspect ratio of the camera image, since the widget size and camera image size are not fixed.
